# Always validate this file using http://lint.travis-ci.org/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse; fi"
  - python setup.py install
script: nosetests
