# Always validate this file using http://lint.travis-ci.org/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies (we use true as a no-op)
install: true
# command to run tests
script: nosetests
